"""Change patient phone uniqueness to be per-hospital

Revision ID: 1227c9fc9437
Revises: 27212debd4d5
Create Date: 2025-08-24 16:56:25.639095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1227c9fc9437'
down_revision: Union[str, Sequence[str], None] = '27212debd4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=True)
    # ### end Alembic commands ###
