"""Add ON DELETE CASCADE to hospitals foreign keys

Revision ID: 161426f9cf07
Revises: f6668834a4fd
Create Date: 2025-08-24 11:21:41.873734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161426f9cf07'
down_revision: Union[str, Sequence[str], None] = 'f6668834a4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospitals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('hospitals_name_key'), 'hospitals', type_='unique')
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=True)
    op.drop_constraint(op.f('uq_patients_phone_hospital'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=True)
    op.drop_constraint(op.f('patients_hospital_id_fkey'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_hospital_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_hospital_id_fkey'), 'users', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key(op.f('patients_hospital_id_fkey'), 'patients', 'hospitals', ['hospital_id'], ['id'])
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.create_unique_constraint(op.f('uq_patients_phone_hospital'), 'patients', ['phone_number', 'hospital_id'])
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.create_unique_constraint(op.f('hospitals_name_key'), 'hospitals', ['name'])
    op.alter_column('hospitals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
