"""Change patient phone uniqueness to be per-hospital

Revision ID: 27212debd4d5
Revises: d05bc9f528ba
Create Date: 2025-08-24 16:53:35.164705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27212debd4d5'
down_revision: Union[str, Sequence[str], None] = 'd05bc9f528ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_phone_hospital_uc', 'patients', ['phone_number', 'hospital_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_phone_hospital_uc', 'patients', type_='unique')
    # ### end Alembic commands ###
