"""Add prescriptions relationship to hospital

Revision ID: 4867c7991470
Revises: 3f1d09b25acc
Create Date: 2025-08-24 16:37:59.172867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4867c7991470'
down_revision: Union[str, Sequence[str], None] = '3f1d09b25acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
