"""Add hospital_id to patients table

Revision ID: 4d83457e3989
Revises: [the_previous_revision_id]
Create Date: 2023-XX-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d83457e3989'
down_revision = '2bcfde2ebdba' # Make sure this matches the file
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- THIS IS THE FIX ---
    # We perform the migration in three stages to handle existing data.

    # Stage 1: Add the new column, but allow it to be NULL for now.
    print("Stage 1: Adding nullable hospital_id column to patients table...")
    op.add_column('patients', sa.Column('hospital_id', sa.Integer(), nullable=True))
    
    # Stage 2: Update all existing patients to belong to a default hospital.
    # We will assume the first hospital created has an ID of 1.
    # If you have no hospitals yet, create one first before running this.
    print("Stage 2: Assigning all existing patients to default hospital (ID=1)...")
    op.execute('UPDATE patients SET hospital_id = 1 WHERE hospital_id IS NULL')

    # Stage 3: Now that all rows have a value, alter the column to be NOT NULL.
    print("Stage 3: Making hospital_id column non-nullable...")
    op.alter_column('patients', 'hospital_id', nullable=False)

    # Autogenerated changes that are safe to keep:
    op.create_foreign_key(None, 'patients', 'hospitals', ['hospital_id'], ['id'])
    op.create_unique_constraint('uq_patients_phone_hospital', 'patients', ['phone_number', 'hospital_id'])
    op.drop_index('ix_patients_phone_number', table_name='patients')


def downgrade() -> None:
    # Revert the changes in reverse order
    op.add_column('patients', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_patients_phone_hospital', 'patients', type_='unique')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.alter_column('patients', 'hospital_id', nullable=True) # First make it nullable
    op.drop_column('patients', 'hospital_id') # Then drop it