"""Add keys and relationships to prescription line items

Revision ID: d2712c96bac5
Revises: d2314936284f
Create Date: 2025-08-23 00:06:25.954131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2712c96bac5'
down_revision: Union[str, Sequence[str], None] = 'd2314936284f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescriptionlineitems', 'instructions',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('prescriptionlineitems', 'status',
               existing_type=postgresql.ENUM('GIVEN', 'PARTIALLY_GIVEN', 'NOT_GIVEN', 'SUBSTITUTED', name='dispenselinestatus'),
               nullable=False)
    op.alter_column('prescriptionlineitems', 'prescription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prescriptions', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prescriptions', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prescriptions', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('prescriptions_visit_id_key'), 'prescriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('prescriptions_visit_id_key'), 'prescriptions', ['visit_id'])
    op.alter_column('prescriptions', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prescriptions', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prescriptions', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prescriptionlineitems', 'prescription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prescriptionlineitems', 'status',
               existing_type=postgresql.ENUM('GIVEN', 'PARTIALLY_GIVEN', 'NOT_GIVEN', 'SUBSTITUTED', name='dispenselinestatus'),
               nullable=True)
    op.alter_column('prescriptionlineitems', 'instructions',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
